name: Deploy
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Init submodule
        uses: actions/checkout@v4
        with:
          repository: thingylabs/denokv-bridge
          path: utils/denokv-bridge
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: 'deno task build'

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ (github.ref == 'refs/heads/main') && 'sternvoll' || 'sternvoll-dev' }}
          entrypoint: 'main.ts'
          root: '.'
